logging:
  level: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    validation-query: select 1;
    maxActive: 1
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none

reader:
  datasource:
    url: jdbc:mysql://localhost:3306/testnbi
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    validation-query: select 1;
    maxActive: 1
    
batch:
  size: 1000
